- name: Create folders in jenkins for creating all components
  community.general.jenkins_jobs:
    config: "{{ lookup ('file','templates/jenkins-folder.xml') }}"
    name: "{{item}}"
    url: http://3.237.170.121:8080/
    user: admin
    password: admin123
    loop: "{{folders}}"

- name: Create jobs in jenkins
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{pipeline_jobs}}"
