- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file','templates/jenkins-folder.xml') }}"
    name: "{{ item }}"
    url: jenkins.devopshemasri.online:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: Create jobs in jenkins
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"
