- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file','templates/jenkins-folder.xml') }}"
    name: "{{ item }}"
    url: http://172.31.5.121:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: Create multibranch jobs in jenkins
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Create Single Pipeline Jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"