- name: Create folders
  community.general.jenkins_job:
    config: "{{ lookup('file','templates/jenkins-folder.xml') }}"
    name: CIpipelines
    url: http://3.237.170.121:8080
    user: admin
    password: "{{jenkins_password}}"


- name: Create jobs in jenkins
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"
