- name: Create Config file - {{item.dir}}/{{item.name}}
  ansible.builtin.template:
    src: s-jobs.xml
    dest: /tmp/s-jobs.xml


- name: Create Job - {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-jobs.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.5.121:8080
    user: admin
    password: "{{jenkins_password}}"
